{% set name = "astral" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astral-{{ version }}.tar.gz
  sha256: e93b491c1e4f53686c73284438b35fb323de303e4b14767d8fadcc15c29b6ff3

build:
  skip: true  # [py>=400 or py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - dataclasses  # [py<37]
    - backports.zoneinfo  # [py<39]
    - tzdata  # [not win]

test:
  imports:
    - astral
  commands:
    - pip check  # [not win]
  requires:
    - pip

about:
  home: https://github.com/sffjunkie/astral
  summary: Calculations for the position of the sun and moon.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

  description: |
    Astral is a python module for calculating the times of various aspects of the sun and moon.
  doc_url: https://astral.readthedocs.io/en/stable/index.html
  dev_url: http://github.com/sffjunkie/astral

extra:
  recipe-maintainers:
    - hajapy
    - jan-janssen
